apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: bradley.reynolds@darbia.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:      
      name: letsencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
