---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: dragonfly
  name: mainframe

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainframe
  template:
    metadata:
      labels:
        app: mainframe
    spec:
      containers:
        - name: mainframe
          {{- include "vipyrsec.image" .Values.dragonfly.mainframe.image | nindent 10 }}
          envFrom:
            - secretRef:
                name: dragonfly-mainframe-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
