---
apiVersion: v1
kind: ConfigMap

metadata:
  name: coredns-custom
  namespace: kube-system

data:
  prom.server: |
    prom.vipyrsec.com:53 {
      hosts {
        10.124.0.2 prom.vipyrsec.com
        fallthrough
      }
    }
  loki.server: |
    loki.vipyrsec.com:53 {
      hosts {
        10.124.0.2 loki.vipyrsec.com
        fallthrough
      }
    }
  grafana.server: |
    grafana.vipyrsec.com:53 {
      hosts {
        10.124.0.2 grafana.vipyrsec.com
        fallthrough
      }
    }
