---
apiVersion: v1
kind: ConfigMap

metadata:
  name: coredns-custom
  namespace: kube-system

data:
  loki.server: |
    loki.vipyrsec.com:53 {
      hosts {
        10.124.0.9 loki.vipyrsec.com
        fallthrough
      }
    }
  prom.server: |-
    prom.vipyrsec.com:53 {
      hosts {
        10.124.0.9 prom.vipyrsec.com
        fallthrough
      }
    }
