---
apiVersion: v1
kind: ConfigMap

metadata:
  name: dragonfly-mainframe-opengrep-shadow
  namespace: dragonfly

data:
  ENVIRONMENT: staging
  OPENGREP_SHADOW_API_ORIGIN: https://dragonfly-staging.vipyrsec.com
  OPENGREP_SHADOW_ENABLED: 'false'

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: dragonfly-bot-opengrep-shadow
  namespace: discord

data:
  DRAGONFLY_OPENGREP_SHADOW_ENABLED: 'false'
