---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: discord
  name: bot

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: ghcr.io/vipyrsec/bot:sha-869821537d8f19d2265a97e3bcc04babec580f03@sha256:e8165bf64c8d3fa3aab531deff8d39f2b9d85a97cef64489d660fc1eb5a95917
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: bot-env
            - configMapRef:
                name: dragonfly-bot-opengrep-shadow
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
