---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: discord
  name: bot

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                namespaces:
                  - dragonfly
                labelSelector:
                  matchLabels:
                    app: mainframe
                topologyKey: kubernetes.io/hostname
      containers:
        - name: bot
          image: ghcr.io/vipyrsec/bot:sha-c88873535cfd3398c8326c8a6bc6e769701b821d@sha256:4ad61264d725efd012d025d7dd397cb49c8de482821f71b3829f2e6d61fb3d24
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 256Mi
            limits:
              memory: 512Mi
          envFrom:
            - secretRef:
                name: bot-env
            - configMapRef:
                name: dragonfly-bot-opengrep-shadow
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
