---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: discord
  name: bot

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: ghcr.io/vipyrsec/bot:sha-18f878aedbb99f5570f1c2e5b7c4d28e3fff42af
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: bot-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
