---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: discord
  name: bot

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          {{- include "vipyrsec.image" .Values.discord.bot.image | nindent 10 }}
          envFrom:
            - secretRef:
                name: bot-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
