---
apiVersion: v1
kind: Secret

metadata:
    name: dragonfly-client-env
    namespace: dragonfly

data:
{{- $ctx := .Values.secrets.dragonfly.client -}}
{{- range $key, $value := mustMerge $ctx.devEnv $ctx.env }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
