---
apiVersion: v2
name: vipyrsec
description: A Helm chart to automate the installation and configuration of our dependencies.
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: ~4
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: ~v1
    condition: cert-manager.enabled
  - name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server
    version: ~3
  - name: alloy
    repository: https://grafana.github.io/helm-charts
    version: 1.0.1
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.29.0
    condition: loki.enabled
