apiVersion: v2
name: vipyrsec
description: A Helm chart to automate the installation and configuration of our dependencies.
type: application
version: "0.1.0"
appVersion: "0.1.0"
dependencies:
- name: ingress-nginx
  version: "4.7.1"
  repository: "https://kubernetes.github.io/ingress-nginx/"
- name: cert-manager
  version: "v1.12.0"
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
