apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dragonfly
  name: reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      containers:
        - name: reporter
          image: ghcr.io/vipyrsec/dragonfly-reporter:edge
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dragonfly-reporter-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
