---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: dragonfly
  name: reporter

spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      containers:
        - name: reporter
          image: ghcr.io/vipyrsec/dragonfly-reporter:bb1f612c75ce88b635f6e58b1614edfb8a486ce7
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: dragonfly-reporter-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
