apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dragonfly
  name: mainframe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainframe
  template:
    metadata:
      labels:
        app: mainframe
    spec:
      containers:
        - name: mainframe
          image: ghcr.io/vipyrsec/dragonfly-mainframe:ddd82999246f1830bbfb0f98940f3b58bbef1388
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dragonfly-mainframe-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
