---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: dragonfly
  name: mainframe

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainframe
  template:
    metadata:
      labels:
        app: mainframe
    spec:
      containers:
        - name: mainframe
          image: ghcr.io/vipyrsec/dragonfly-mainframe:sha-9da755602f857d4bdd548806ef5ae0ce9bf49fe7
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: dragonfly-mainframe-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8000
