kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: grafana
  labels:
    app: grafana
spec:
  storageClassName: do-block-storage
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
