---
secrets:
  dragonfly:
    client:
      env:
        RUST_LOG: ENC[AES256_GCM,data:evr34oV0FqTJxEkHpXIoqx8cFG5naIOstZl1bvNm,iv:LqES9AK30o9HxFdnQE5y4p8KQSYgk01n7mT1nJHQcVI=,tag:MRNXJF7GHdzsac+W8tFeow==,type:str]
      devEnv:
        DRAGONFLY_BASE_URL: ENC[AES256_GCM,data:dI3a7RNJFFqW4FZ88zW/gn1hsDQ/uOFZ4LoCW2uJ9cu5YAY9C9skG2VQjuq/ZF7F9Q==,iv:r745rBqzMnTt6515rcygXXFLVlzQcaqKCQvTFMHwacc=,tag:2zRlxD5U6pRb49SA4KT0iA==,type:str]
        DRAGONFLY_AUTH0_DOMAIN: ENC[AES256_GCM,data:HtZxfAbFXfSW2tf0gaKlVT61HIwSznW4lg==,iv:MBJnT+Ujfmzw+JxLp7h5S62TMKA6AS4W/naBjTbP0Vg=,tag:O1w+OIsLiRMVMM4ur2b8OQ==,type:str]
        DRAGONFLY_AUDIENCE: ENC[AES256_GCM,data:nprkxoM9iHpiN1HzPxGXGQTn9du1XezBFIqE996T+Wk=,iv:4VM0qrGLdjq8a9mQpUXRJJjECHgSC5irmqYbbxEdU0A=,tag:PYDi4/hXIAi05LEFr1koJg==,type:str]
    loader:
      env: {}
      devEnv:
        BASE_URL: ENC[AES256_GCM,data:iYN9fx63jZnEvJIb1eQmy93+Yi9zdp4HoJFHNbA2JtCMD4FGvl25HcEvfl4vsPsWqQ==,iv:mFHgv0vOtQJNJketfRXbegp3TlimktWeDNFgwp4sxpg=,tag:jMgysDSOV061MSS3VQqL2Q==,type:str]
        AUTH0_DOMAIN: ENC[AES256_GCM,data:go6+vT1/2ZTgXiWas5MN8Im30mr48oOb4g==,iv:+x0Aqqj9jP+deP2Z8/A/wxEqFvxijgmcU85p+dfm01U=,tag:JoJVQbgw+192kzLd5r4frw==,type:str]
        AUDIENCE: ENC[AES256_GCM,data:ROhkXAg+d8AX4bVA55bAbhBVvrPXtg0YKy4Aao444WI=,iv:n1N7lZie9G9Pl6Plh7sVHK1ZPLtc3TIDUmOR/1G8PII=,tag:lExTuCiVcKcCwPTfkvtw/A==,type:str]
    mainframe:
      env:
        DB_URL: ENC[AES256_GCM,data:sa+KH7cXjGKVEUmnPXewhmuJXRtC+RhbhStw08usz5j5lB90WLcIaVvPmU18b7g3PiLHXbffBi6ZebZHIUc=,iv:U+j5FXbkoAhiqV5IWEW706nKpNuiGAOc/Jc1bUNSyUg=,tag:GNFcvh4iatJ+Y3J5ANbM+g==,type:str]
        MICROSOFT_TENANT_ID: ''
        MICROSOFT_CLIENT_ID: ''
        MICROSOFT_CLIENT_SECRET: ''
      devEnv:
        AUTH0_DOMAIN: ENC[AES256_GCM,data:8ngpNhzkSkVyVQG4zzsOyJkQS+IQeor1Fw==,iv:v6pUNLU2LtuQtdGkslmaddg0t0MIT7zkrnB1jTZ+g0E=,tag:Rs7bCFSfZOh+BWhGbg6bLQ==,type:str]
        AUTH0_AUDIENCE: ENC[AES256_GCM,data:xmW9rovCGgo7wfWQNt3NDe1cUpIzvS114QVXiAu5jNg=,iv:Sw/lIiQ/AmPccxkgwBs/vx7cYpeKOMr4MJsmCKZQEOI=,tag:LZZ4dnGmovpQksxdMJixyQ==,type:str]

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14x4ptx2a6tmudhx4t89r9xzxjkqmcaf36q8rkvh9mqwetl0sc9sqrqqe6k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVB0bU5QTFlEUjNJVDFY
        U1BySTdCQ2NwY2VTeThJRy96UWhkTlJQb0ZNCkZvT0ZMNmQ3TmYycmgyVUZ6NXpN
        LzV2RlZQaXNkYWhuR0xuRnBVbnFHMVUKLS0tIGRFbytDRktiT0x3QnFDeFg4aDhW
        UkpybGw0bkZVSUJHVUNNTG9ZU2xoS3MK/gLno4tf/oX0D6tWU4M7Dyr/eJPHF3j3
        JGIqN91/7g21SEJdtL3CgqGPy4ar3H5gWA++Bs64oXkqK/qkcp+cLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-11-28T18:38:32Z'
  mac: ENC[AES256_GCM,data:d05MMMetX5E9QE6lCaRls1lGJ7C6o1dfZa9Ykq8710u+2tSJa0ZqPw3PT0l2d81u6ke59U6rrUk59/jGm1JBha7djuqqNcQ61ETz3gdh+Gj7A4cKMiXJMDqQlbXnA9fVTdOZF3uhacfGM7ULAZCU3pR0LzFo08urHoyh5b6Y78A=,iv:YBguAKeHKNBlQ8KUGZWTXzFife2uFh4BQh6MDvZcNrE=,tag:JnrwsHOpAlbkDjAR1D4xEw==,type:str]
  pgp:
    - created_at: '2023-11-28T20:53:17Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hF4DlfyRzrzFfXASAQdAw++ixwAeYKNYSVySwz/vHVZwMtqfGdiP8KCmNL5J0m4w
        u3dFEd+x+htPXdq4/pV/QKr49EqJJei3e6iPMfqISYQwSsaj/xo86/RVzyjMOnqG
        1GgBCQIQOD/F0dv7mb56ZlHHl2lM0MUKBYnL2qDYVSt4KTQRsz7AOW+KYOGizcVZ
        J4m2dsTU7r/PK5Yqiw1IWmshr5sfePohLirnH/nXmDkVlKM80h8ugh1TB1Y3gqXU
        WXBhbSk5+5bBbQ==
        =vFUc
        -----END PGP MESSAGE-----
      fp: 57C08B3692574B9AC337B4C01266FEE4207113D2
    - created_at: '2023-11-28T20:53:17Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA9CgBykT/EMtARAAl4bEyPcF1YMKJqCBAV2Q57wJX2lpAcj+sRB/d+olhRe1
        ukZH8WGGiq/ZQo5oXYWJylWYsD8Or++nzm7++YHowfZXXwz9fWUq8pmH+PmUl6eT
        PuftF+2X7+aAQ98h3Tf8cuAKGS0VyzkFK32Uj8q915UTpqVjOqCfzXegUN1l29xa
        yXfV4e/gII9FOslAsm6CZP3hlM95NmGqY/wL1sPIM3urSjuw3gXDLgLpPWMiMjxd
        Nd1iWBJqO0OlxvlnQp8QAy8fvwCDKZ1/6hh06ZG1PlxVltqUUdoaXmQ9eD7mNNp4
        GGigF/K7zPScZnqK3ulDCW4QN04DcWiaC6XTSRChnjPkGjs6TWrdakmBEARblpJr
        K86BRZsKHlH+3pi73tbmqQGox7GDvXe82nEs5Q6BjoU8+SaR+yiyFha8ee5pTaDs
        nJI0hHN9Xa5Q+UN0yh9JIDpXpfSZPy3gOQW//vo+GluyfpXuyW1BqEx9MygcdWgK
        u6UGjyxYmhnyTr3iN/YPiqyRcM+duBCKF/8R2hjVbJ4aR4onQ7XybD4mwFnKmskl
        SrYnQVnjkITufiEeQ9pkp2LsJ5PiKorjkOrdx42eNb/Lqy/bARbbsJ2l3zLA0S0A
        7FES8eMtZ3RofkMqVfGWIArhEQ/bPOZqpER88VlKQ8FRvWodLOfPonM2pnDtaiXS
        XgH4pDx/onmgIoYv6aTPL42iT3HLpUJkjjifiwbLi4kCwdCrSLo1jjQgGmwb5zgk
        oBCXrpqxm+bZo/z1lBhuRJ0tuEpsLvmMSrq61uXR3JclPwX26DhDNwd3RoDcXM8=
        =vJnc
        -----END PGP MESSAGE-----
      fp: 0B880EFC9332E26F61DF893CBC923A430F78DDAB
  unencrypted_suffix: _unencrypted
  version: 3.8.1
