---
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: dragonfly
  name: dragonfly-loader

spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dragonfly-loader
              image: ghcr.io/vipyrsec/dragonfly-loader:sha-9f67b5bfcab22089deef147902532c3c9f17d90b
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: dragonfly-loader-env
          restartPolicy: Never
