---
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: dragonfly
  name: dragonfly-loader

spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: dragonfly-loader
              image: ghcr.io/vipyrsec/dragonfly-loader:sha-7acd34813cc2c74e0c4849b1b6c2a1c5fc651beb
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: dragonfly-loader-env
          restartPolicy: Never
