---
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: dragonfly
  name: dragonfly-loader

spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dragonfly-loader
              image: ghcr.io/vipyrsec/dragonfly-loader:sha-fc9128434c0f15b90e7f0ec686bd1932f3c5fd4a
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: dragonfly-loader-env
          restartPolicy: Never
