apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dragonfly
  name: dragonfly-loader
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dragonfly-loader
            image: ghcr.io/vipyrsec/dragonfly-loader:909810f18dfb9d0218c73b7e3fb229127222d102
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: dragonfly-loader-env
          restartPolicy: Never
