---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: vipyrsec-core-devs

rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - list
      - get
      - patch
      - update

  - apiGroups:
      - apps
    resources:
      - daemonsets
      - replicasets
      - deployments
    verbs:
      - list
      - get
      - patch
      - update

  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - get
      - patch
      - update

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - get
      - patch
      - update
