---
secrets:
  discord:
    bot:
      env: {}
      devEnv:
        AUTH0_BASE_URL: ENC[AES256_GCM,data:ABWJe63DEV46IbQOwhE5WvnfWilI/28VWZSvIbrAsygR/EuX3Q91dCuMTiMtAixuWA==,iv:hRp1mG2vmA+LOxQIuQwMlwBs6wbWWYYFEcsFOxLEY8I=,tag:zQLJposjxWg6k7P9UgyYRA==,type:str]
        AUTH0_AUTH_URL: ENC[AES256_GCM,data:0HR/s8A7chjRxayolzPvCNFq2eZPV8o3IS/9+jqOjPdQ2+PFu3eGvgkbe9qO,iv:gDl56O3A8WVQntxRKPSsc7kdPsvR2tHK9/krUzaYZcU=,tag:zXAevKGTZ5atjI7atIKWUA==,type:str]
        AUTH0_AUDIENCE: ENC[AES256_GCM,data:pWrXAjWjqPCspIBVfyno/J4DLaHXvvvQdLMQUFaGNME=,iv:Yo53ecRWc2EYcumsp8I9oc3VNA5fzjwMRJ2r+A+Vl+g=,tag:Se5lSFWIPJ6rSWaOWtf/yw==,type:str]
        DRAGONFLY_API_URL: ENC[AES256_GCM,data:egfYHo2zDXAUhdS7ZkG0BW68YU78O1V+AY+96banuKqCHbZivf9tkTOtKVD7uaw6aw==,iv:2DlljjAO5DjWyQEX7rxgHIoTK7praD/9TObn/pHMQu8=,tag:Y0EqEW6evnji1rjJIg+xGw==,type:str]

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14x4ptx2a6tmudhx4t89r9xzxjkqmcaf36q8rkvh9mqwetl0sc9sqrqqe6k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Mkk5NkFSWkx2YkYxQVJX
        ZmcwMzRGL0tZUFg1YUlubFZsRFNLR3hPb0RFCm5BRWFmQ0RPZ3lhZzRCK3FtdThJ
        SCtsaXZwWU9LeXpxdUdyYTl0NnJLM0UKLS0tIGcrNEZoaERjY2oxejVMYURhd3Nm
        bm9ZdzFKLzR5MytjODdSVnFjODM0QkUKCr266j9LN3chZEXuPnR74P/mpaooU9v3
        xh4UjHF7WKZl29maOkdGvDKuo+BPsidPi+Mu9jiOXANjAt27hhhQvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-11-28T18:45:33Z'
  mac: ENC[AES256_GCM,data:fCPlE/CPiFIsi3JHgH+5uKXzJfwUuURBq9oJEOPXCneF5aX1nlj/Lni94ybktYy6+0lzr3mN4qB9paMehoH9F9hxwAdxO0vZtNIA/JER8pXdStWD8mhvT1sY2ovJnO952ypoFDk8Ix488kxA0n+b18LjRtsGOEQiq2FIO5ZMx2A=,iv:vS5CPx1yupGhAIMD2/kDfsM+Hvy6KxT8HeU+/xzhTyo=,tag:LFRILlW6tO/6piyrqTivEQ==,type:str]
  pgp:
    - created_at: '2023-11-28T20:53:15Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hF4DlfyRzrzFfXASAQdAc2Nrk1jmQRZ4jlZDPivcPVcxrbq/pEKQHUjS9taYf0Uw
        UqA2JWtFMHGB7FJaEBCIEUWsJe3RWnKLW+1rkgm7AJAuuS0avN6r+olnjllZYu7j
        1GgBCQIQ+39ZnEcOro8qlzRx+4+7FkNS7h9FT3XDNMmy6HCf3VvqikXvq9A1fX7I
        WAyPyeDfeqcM6CwgP7dEPdES7n0KySr+vtqYwot2O6Pft+Lu2xoXldZ+98b2AlrI
        opasSsiURgfeBA==
        =xIBW
        -----END PGP MESSAGE-----
      fp: 57C08B3692574B9AC337B4C01266FEE4207113D2
    - created_at: '2023-11-28T20:53:15Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA9CgBykT/EMtAQ//XvRAn6xJ+iVtCNTMoN+Zme3p+G8owIKNrM9InNYkE3Dj
        JH2XcWW856QJnPqzrj/i9OZzsoDxvWKToEkLPkksBLN6MGnt6J86/XXWYadzxo/e
        jd0G+Ppqg46XbvAozPZkC/VzlG6yaX1QYepWROyj/hLz3nygju52yC19+ehN2om0
        WYydz6YwYy8ccx3D3u8UgvPDvgT5Lz5WoboiBrMsDfkX7aU02OY6kmQUEeUqNh6w
        bQzZuZ7xi2QQJRduDOVB7ILcxjzy1c7NtnLGbM81GbSWo4VPoiku1XHF7e4YbNqZ
        BlmcBRzbozJtPRRavUGXpi2esEWK6EsCorN1GTWZIOZfgvOeOe25t1N+kXteZg7g
        GBxiZzugX+1Ih/9JpwEEViJ6oAjgthZZb3bR7h44QneezcPhJdW14gmNgVM0kEcI
        BmJ1jk48moc3e39OpLYLLtjDGgwPC+ntA+ZE3dtT/j6EBa9352zBvac+WBa/Xd22
        sAgRtJzfdb5dr7cizbGzpW1bWoSK3QR0YegZiYOxPKWFBM9JkqArhre+myhpaq6Q
        PsjIOiGR7oKjIgLQAf5E2pOY0bkIWdwzLoZfofIXTsBSKhj98joLxxVEQkXEmZ5s
        prq5tBZBzBODpk3BOXEWIKsxTC7qtUua/D/29B/PBgFaDYtp+MJSyjlX3n6KTezS
        XgFztlNGkrw9abRtTaDfHM3DpjWIL1g0uS5W91Wdj4iP58xBMuevNegmutQbmHmI
        sEQL3FbE7wkOjsK/VAdWlpJKUaVfmwAu/89p5qsbQvMMQY6F7JAv5x1r7xO3+ys=
        =XmnS
        -----END PGP MESSAGE-----
      fp: 0B880EFC9332E26F61DF893CBC923A430F78DDAB
  unencrypted_suffix: _unencrypted
  version: 3.8.1
