---
secrets:
  discord:
    bot:
      env: {}
      devEnv:
        AUTH0_BASE_URL: ENC[AES256_GCM,data:ABWJe63DEV46IbQOwhE5WvnfWilI/28VWZSvIbrAsygR/EuX3Q91dCuMTiMtAixuWA==,iv:hRp1mG2vmA+LOxQIuQwMlwBs6wbWWYYFEcsFOxLEY8I=,tag:zQLJposjxWg6k7P9UgyYRA==,type:str]
        AUTH0_AUTH_URL: ENC[AES256_GCM,data:0HR/s8A7chjRxayolzPvCNFq2eZPV8o3IS/9+jqOjPdQ2+PFu3eGvgkbe9qO,iv:gDl56O3A8WVQntxRKPSsc7kdPsvR2tHK9/krUzaYZcU=,tag:zXAevKGTZ5atjI7atIKWUA==,type:str]
        AUTH0_AUDIENCE: ENC[AES256_GCM,data:pWrXAjWjqPCspIBVfyno/J4DLaHXvvvQdLMQUFaGNME=,iv:Yo53ecRWc2EYcumsp8I9oc3VNA5fzjwMRJ2r+A+Vl+g=,tag:Se5lSFWIPJ6rSWaOWtf/yw==,type:str]
        DRAGONFLY_API_URL: ENC[AES256_GCM,data:egfYHo2zDXAUhdS7ZkG0BW68YU78O1V+AY+96banuKqCHbZivf9tkTOtKVD7uaw6aw==,iv:2DlljjAO5DjWyQEX7rxgHIoTK7praD/9TObn/pHMQu8=,tag:Y0EqEW6evnji1rjJIg+xGw==,type:str]

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14x4ptx2a6tmudhx4t89r9xzxjkqmcaf36q8rkvh9mqwetl0sc9sqrqqe6k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ0VxWklVNDhGb0kydXMv
        ZVBiK2p5WDU1RUhLdHo4NzNRYlBneGdFbkJjClZiRllVMlN2OGdvVjc4ZTlsWDhp
        LzJmczIxQVU4SFVwU2ZTVXRSdG5tVjAKLS0tIGJMY0djN3IxcWxnNktxdGgyRjMv
        NndQZ2IwYWZAndDMrSnR3eTB3dkZmRUUK22LLIsHT8r03uEoqrPNBPzzvLIAHsMkV
        1naWNIw0QBqdfaBEdTBPw/yr6H/tH3A086N2O6bDgaTNMF5tZXfqvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-11-28T18:45:33Z'
  mac: ENC[AES256_GCM,data:fCPlE/CPiFIsi3JHgH+5uKXzJfwUuURBq9oJEOPXCneF5aX1nlj/Lni94ybktYy6+0lzr3mN4qB9paMehoH9F9hxwAdxO0vZtNIA/JER8pXdStWD8mhvT1sY2ovJnO952ypoFDk8Ix488kxA0n+b18LjRtsGOEQiq2FIO5ZMx2A=,iv:vS5CPx1yupGhAIMD2/kDfsM+Hvy6KxT8HeU+/xzhTyo=,tag:LFRILlW6tO/6piyrqTivEQ==,type:str]
  pgp:
    - created_at: '2023-11-29T12:51:20Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA9CgBykT/EMtAQ//ftSZlIJ4gp1+2qENJIyveoTKx8IS/pC+Z4ixuya+YVeL
        XENteD93efYXk4dbyJFvlomndBqr4RjEsMWyx5bzD7yrBthuTP89g1qlvydzt8I9
        hkQd/bdJmZ9fV0AcWXkp2NaMq8BuCyvE98/EYn1DWp3SuYc8T3l3vBfsJy75Ro9+
        zqREKxWxbfuwS8G56ODT2nQ2tNURwSPRHeXCcJLtizvKhSmI0E3XxltppD4AnZ4y
        fSrMrmypC1Gpe1Cc9qSKAYP1X9Bx8VE+zW2Vy4GStXVtqaf2e2Xg73P9A8iN/z7b
        Hd1M8ueRKxSezCcSm/pXvx2AufDIPuzqZ7HnQTLsL6aEaI2IRYHnMSrAJWK/dmaj
        UBzu4KxlVGAbES2f//IvggRdBM3haxJAqpO700fbuj/hKxVz9uAtXQ1l0ucVtBOA
        ivDlnARaNPDgSNoJ5xXnHKcPPXpk3ZTe2F78bfUJVifI0IiA8S76vp80pHUqarNx
        JtePBPMbtBX3bGNYanKP9rSG7EcY7UKOAGtbF28VsLZiEA/5EiRHhLG/hp+0Mg6q
        zsVbA0DRbcAsRO3SbEtNG0yTo3VKe2R+rvqJEHjSyDbqpI9mPRgnN2XTDsa09Y91
        E5an6PJHfW9v4unzkMD8dR8Siu9M1GXlrs2br1X0GG/nKwpEoWFXfutOoQ6S39TS
        XgERkr5ARLerscs0F7ikh2XUWMcdYAACDOqdA/eW4m0+/rV/q0Hs6uzkaGOroyGS
        gT7aa0exHxAGC3ekSZp/87UJ6RNxo7coxVxz3AcagJ0zQBSU807ECjzBp0Wq47g=
        =sk8u
        -----END PGP MESSAGE-----
      fp: 0B880EFC9332E26F61DF893CBC923A430F78DDAB
    - created_at: '2023-11-29T12:51:20Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hF4DSiTzi/WFmIASAQdA1XlrR9T1vgFTLgmF6hQTs1awPgSVT5ZLXyjem5rcG2gw
        /JMRgLivJO5EYn2BRRjijDeEG0KLnjS4WIlTb5I/Yxjirv/hMYpnhTYcjniYOcH0
        1GgBCQIQj1I7Wu8rDYz6kTPBsJMUR5btp15SbM4mgmKL1KbRbqZqokRVaD0Lz7QY
        2SyUjTrowva4DrGysDe1Gl1GKJ6vqcuyYLzfcyaLHUP8kZ+0eTYPlm377ax37D0c
        nZenvQk0eo2O1w==
        =qlX2
        -----END PGP MESSAGE-----
      fp: 11BB4AACCE8071272E24867CA3AB5109A20000D3
    - created_at: '2023-11-29T12:51:20Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hF4DlfyRzrzFfXASAQdAdkF/EsKQvF7z0YY3Llj+7J0k2DE5eJEJrsm7TN3+hDgw
        8zE0wpZz4qArpW3KlNiZ+dAqTZIARuSj8yCyiyGO2MZbGo9KedE0aVg1bn3E/Pic
        1GgBCQIQF+zyBlwsrTZERN0uXpJ6wLiutdYkelLNgODqxxaJko/8HpS0k3DuDarS
        +4RThVMmLH8j2HUsfva2nslRT14wB9hXvkrY1h5QxIuT9tPT1xWFnfGiA6b31vG+
        DOlPzOEJ7bjieg==
        =y0sM
        -----END PGP MESSAGE-----
      fp: 57C08B3692574B9AC337B4C01266FEE4207113D2
  unencrypted_suffix: _unencrypted
  version: 3.8.1
