---
secrets:
  discord:
    bot:
      env: {}
      devEnv:
        AUTH0_BASE_URL: ENC[AES256_GCM,data:ABWJe63DEV46IbQOwhE5WvnfWilI/28VWZSvIbrAsygR/EuX3Q91dCuMTiMtAixuWA==,iv:hRp1mG2vmA+LOxQIuQwMlwBs6wbWWYYFEcsFOxLEY8I=,tag:zQLJposjxWg6k7P9UgyYRA==,type:str]
        AUTH0_AUTH_URL: ENC[AES256_GCM,data:0HR/s8A7chjRxayolzPvCNFq2eZPV8o3IS/9+jqOjPdQ2+PFu3eGvgkbe9qO,iv:gDl56O3A8WVQntxRKPSsc7kdPsvR2tHK9/krUzaYZcU=,tag:zXAevKGTZ5atjI7atIKWUA==,type:str]
        AUTH0_AUDIENCE: ENC[AES256_GCM,data:pWrXAjWjqPCspIBVfyno/J4DLaHXvvvQdLMQUFaGNME=,iv:Yo53ecRWc2EYcumsp8I9oc3VNA5fzjwMRJ2r+A+Vl+g=,tag:Se5lSFWIPJ6rSWaOWtf/yw==,type:str]
        DRAGONFLY_API_URL: ENC[AES256_GCM,data:egfYHo2zDXAUhdS7ZkG0BW68YU78O1V+AY+96banuKqCHbZivf9tkTOtKVD7uaw6aw==,iv:2DlljjAO5DjWyQEX7rxgHIoTK7praD/9TObn/pHMQu8=,tag:Y0EqEW6evnji1rjJIg+xGw==,type:str]

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14x4ptx2a6tmudhx4t89r9xzxjkqmcaf36q8rkvh9mqwetl0sc9sqrqqe6k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SkM5RWQyNkZ2aUcvU29P
        d0tLU2lHWXdjYURxNlFzZTJnZWhFSjNCVGhrCmlRWkZtVkpEQlFBSW9aZHBxZkJE
        dGJ3V0cvSEdMb0xCNHlNQU1zeVEySTgKLS0tIE1kRWZRcXpHbjFkMGw3ZkxxK2Ru
        YkljT0I2WHhCYmVZaDJ0NmNCeTNuOTAK1vLsx2pddFd0KiU7juqTIn+jHOEd4gDr
        dM7p4VHgKeH8DEmJET5FjCtMOfPt0FMV28t/FihZ7Cjq30NigSBcpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-11-28T18:45:33Z'
  mac: ENC[AES256_GCM,data:fCPlE/CPiFIsi3JHgH+5uKXzJfwUuURBq9oJEOPXCneF5aX1nlj/Lni94ybktYy6+0lzr3mN4qB9paMehoH9F9hxwAdxO0vZtNIA/JER8pXdStWD8mhvT1sY2ovJnO952ypoFDk8Ix488kxA0n+b18LjRtsGOEQiq2FIO5ZMx2A=,iv:vS5CPx1yupGhAIMD2/kDfsM+Hvy6KxT8HeU+/xzhTyo=,tag:LFRILlW6tO/6piyrqTivEQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
