---
secrets:
  discord:
    bot:
      env: {}
      devEnv:
        AUTH0_BASE_URL: ENC[AES256_GCM,data:/HsFO8/sbNb6xHAAcb0rWqejKyb9NosDzkEaeH5gf4QwLMiur1QLv8nwNuytxHAXhA==,iv:GZRfoNI0SH18+nsPrYKMS2o/SUNn9yc4k6I1f4+aVn8=,tag:SQrRHYJP7QHAmSwL10KfaQ==,type:str]
        AUTH0_AUTH_URL: ENC[AES256_GCM,data:ZZ3s0gdmFoJxP0In/VyTvrSZKbTXSSyrFPxiwThAMCA36BWxWHo5mfujrk81,iv:hMLJLeHQgM1EX6/JFacqgYIbHETjuYaUyLp20fFnaXw=,tag:i2SxAYL2LGvAiBQWNzrVmA==,type:str]
        AUTH0_AUDIENCE: ENC[AES256_GCM,data:mwWICXwOy06JlkW9foeEKcP9FlSq0wpULZ2/ZjGS5lo=,iv:mUDom5TZemGxxxpbm9WJy2vDgDOpCw/MjrJpIrR6s58=,tag:vT5A9H4K1v7GN2kqseKZig==,type:str]
        DRAGONFLY_API_URL: ENC[AES256_GCM,data:zAB05ThUf03MRgIpCpNzIFNgtnEQ0XRQCMDQ0vjAmytNbsl6SaC6HAGNqd7yO/fZmw==,iv:WkbVD6f1ZdkLFZpxQe6aJTi2+TYskFrwm5fSmsipL3w=,tag:QkMW/52CIrm53pJP6rPIhQ==,type:str]

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14x4ptx2a6tmudhx4t89r9xzxjkqmcaf36q8rkvh9mqwetl0sc9sqrqqe6k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c3VKSWRqMnNQU1BROVRW
        ODRwNGtPUm9mcG5kM2RMTE5zWTFLa2ovbTJzCldsbjhRL1dERldhSnN5bFhFalZz
        czhmVEtIOXg2eVEzdWdWSlhOeTRJNUEKLS0tIDVHOEh1Q1VCYVZNa25EQkZ2ZlI0
        SklvcWtFTXRGQnBsaXBEa3c1Uk9oVEUK4R/Xpc6lr9jUIZp9fpiXz07namVX0/I+
        FWxDyok3/DUd+kok6O+3McEWna39Xk1oijEye+uqWLw+pqPAm3uYcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-01-01T12:55:51Z'
  mac: ENC[AES256_GCM,data:YTqp9S7+wosZ7tu8RafiWlxhwUZDiB0/5hEc+qYUFsxDnWbn8lI8zYQaZ0MdeSU21La1umq7BLyixjqZY8iU7xLa9DRtkFWBcGlvX/e+wREMsSddzHzArho9Kengh+GM1qlqG8ZryIlVN2hq/z4SxAb9DfhVpEiHrKajxv9GCGM=,iv:UadgSFcRRonmjHlAu6DsogCstVRZlez65QUQ/luvFjo=,tag:awTgmohibLXYkcfSLCZ1cw==,type:str]
  pgp:
    - created_at: '2024-01-01T12:55:50Z'
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA9CgBykT/EMtAQ//Ygahnl43ZKoIcZi5xtd9Z35EkQvDnohdkphXsxTZIKGu
        LguFV/+YZxsU0n0nKvz9sXWsiDrJYLJAYXrHX42PIX5JcoOE10OjmU17krIQVlVC
        4SGUzQY63k0h2dxDxWB9EFbW6BwlELUdzo0j2d2NFkrON5aFFQxREN/JK7vsGg6U
        7j9L4vDpL+AjWvvR9fg5hES3Yu+565gjeLw/PVYio1zPmX6nHTuXJtvwrxzaP+OM
        R2Wu1/BA7A9vJJMExlRkI5uK8Ougbdf3IQ4nBQeIlXd9bNj13tmdgZJDNWusGHVP
        cWWxH+7Epc6sytQ5EHDtoOPze8dhyboTlNMvf3Th0q861EZNtVJkB+eeESn0JDpR
        jnq2fp60mZUQn5g3ImmKdbFAJm0FTisYgx29d8JJG4e6zfMTPifzWVzTQuRaWjZn
        Ca6JQR/GiR4VB7RXoi0QJdcDWC/QB+O6ej1U4DuQC6BtxQKObnE3FKkvxUUN4zFu
        x1d+31mLPcglC+jeT+2g08/g/9R8MjtrSFZNKG4Yy5gX0oFnfxjFwIjqfbhnkEJC
        +HQ64pvRXoyRG2vTHK4YNVRQNvM3KU5B8sApoMek4zQdUqDENy5KdsPSJs8fWW9i
        3elCi6ojITQtxKwFlNktEtwveOCoPPFOKGgG/+Jn4oJmuy1cs2OHxK2nYCIJ9T/S
        XAFN9XwbwNrLbb2W2cn78/T92rZqw/jSJMbxONewfdqOLuDVYqmGm0nj45rHyOJK
        QaIDhtDmO/gUdO/Icy8JBvkACr8sDhtnUEztuyHe3ogbfQY8aREb8n//HYwD
        =M4fi
        -----END PGP MESSAGE-----
      fp: 0B880EFC9332E26F61DF893CBC923A430F78DDAB
    - created_at: '2024-01-01T12:55:50Z'
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DSiTzi/WFmIASAQdA84qUsAOKowxDhGcKs0nRG7slB6jMyEW+om9U7m8T4Qkw
        DIMVxI3asnk26QUVfKbS80umUIiqDl9JAZAnFFS+QdtsKjuzBYJamesX/CmTpUw1
        1GYBCQIQ86O8JMWg9cz5/lusNp5OIUq23zOIwanS3U8Rs0BMh5s/9Td4jeYWjIGu
        6c73jLOy3x4wjAO84+e0zv7PCTC6f7kmwR6/DiSpWIrf6RyBuNjZ/QcuaT1Djof7
        iYO8G9S8vTM=
        =hDov
        -----END PGP MESSAGE-----
      fp: 11BB4AACCE8071272E24867CA3AB5109A20000D3
    - created_at: '2024-01-01T12:55:50Z'
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DlfyRzrzFfXASAQdAUw3Yl1CaCU57lVsr/Nj0iFvZWWhfGE+87XmchtDK9zww
        D3IdeKE35fplPsy5FznQUMafmom7PT2CkiuMPrQZanwNZJHOHSEIFoVk3ksT7Q8e
        1GYBCQIQCOARI0+NItnFAGkLyVX6ktYq65qHEJSEu5rSFTdCJI0cmUOuU2++RwyI
        Jln+eAdXffXNZF3xsnT7DRA/VwAzgsfCS0cbyi9WgR3NAdBuh7C/vv9YlKVfwRTX
        pd/uEqTTs3I=
        =xy2v
        -----END PGP MESSAGE-----
      fp: 57C08B3692574B9AC337B4C01266FEE4207113D2
  unencrypted_suffix: _unencrypted
  version: 3.8.1
