---
name: Kubernetes CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint manifests

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - '1.30'

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version: '1.22'

      - name: Install kubectl-validate
        run: go install -ldflags='-s -w' -race -trimpath sigs.k8s.io/kubectl-validate@v0.0.4

      - name: Lint manifests
        env:
          KUBERNETES_VERSION: ${{ matrix.kubernetes-version }}
        run: |-
          kubectl-validate kubernetes/manifests/ \
            --local-crds kubernetes/crds/ \
            --version "${KUBERNETES_VERSION}"
